spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quickChat
    username: postgres
    password: widad
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


