spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quick_chat
    username: postgres
    password: widad
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true